### PR TITLE
NGSTACK-427 - isExpanded option in field type

### PR DESCRIPTION
**Pull request by MarioBlazek**
This PR implements the `isExpanded` option that controls whenever will form widget be rendered as multiselection or checkboxes.

### CODE REVIEW

**Comment by emodric** [comment]
Does it work? 😄 That is, do I have to test it? 😆😛

**Comment by MarioBlazek** [comment]
Admin part
Screenshot 2020-08-25 at 22 50 46

Frontend part
Screenshot 2020-08-25 at 22 51 48

It works :)

**Comment by emodric** [comment]
Fix the tests and let's merge then! ❤️

**Comment by emodric** [comment]
Thanks @MarioBlazek !

**Pull request merged**
