### PR TITLE
Migration command

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
Symfony version of https://github.com/netgen/enhancedselection2/blob/master/bin/php/migrate_to_database.php.

Might be useful for a migrations from 5.4 to eZ Platform 2.5

### CODE REVIEW

**Comment by emodric** [comment]
Hi @SerheyDolgushev 

If you wish to merge this for usage on eZ Platform 2.5, then this needs to support PHP 5.6. So no scalar and return type hits.

Besides that, I'll trust you that the migration actually works :)

**Comment by SerheyDolgushev** [comment]
@emodric also removed `int` type declarations for arguments

**Comment by emodric** [comment]
Cool! :)

Can you also rebase on `3.x-stable` branch, as `master` is now for eZ kernel 8?

**Comment by SerheyDolgushev** [comment]
@emodric done

**Comment by emodric** [comment]
I presume you tested the command? :)

If so, I can merge!

**Comment by SerheyDolgushev** [comment]
Yep, we are using it on some of our projects :)

**Comment by emodric** [comment]
Good enough for me :)

Thank you!

**Comment by emodric** [comment]
Released v3.3 with the migration command included: https://github.com/netgen/NetgenEnhancedSelectionBundle/releases/tag/3.3.0

Thanks once again @SerheyDolgushev !

**Pull request merged**
